### ISSUE TITLE
System Analysis and Wireframes 

### ISSUE THREAD

**Issue by amorenew** [amorenew/awesome-calculator#1]
To Do List:

**System Analysis:**
- [x] Check different calculator apps in play store.

- [x] Make a list of good calculators features.

- [x] Separate the features into 2 categories A-Most Important B-Options.

**Wireframes:** 
- [ ] Use Most Important Features to make app screens on paper by a pencil.

- [ ] Take a picture of the wireframes by your mobile crop it and put it here.

Note: After finishing any step put it here so we can see the

**Comment by rehammetwally** [comment]
i will do this task in one day

**Comment by rehammetwally** [comment]
System Analysis:
=====================
Calculater Features:
=====================

----------------------------------------------------------------------------------------------------
----------------------------------------- A -----------------------------------
----------------------------------------------------------------------------------------------------
- Addition, subtraction, multiplication, division, percent operation
- Do scientific operations such as trigonometric, logarithmic and exponential functions
- Recording and recalling calculation results
- Saves entries even when closed mid-calculation
- A clear display format and easy to read.
- You can use the backspace key to correct a simple mistake.
- Input up to 12 digits
- Displays your calculations with thousand separators to make it easy to read
- Usable portrait or landscape
- Choose between simple and full keypad layout
- Tap the DEL key to delete 1 character
- Hold the DEL key to clear the entry
- Tap the C/CE key to clear the entry
- Hold the C/CE to clear everything
- Designed for tablets
----------------------------------------------------------------------------------------------------
----------------------------------------- B -----------------------------------
----------------------------------------------------------------------------------------------------
- Customizable themes
- Customizable fonts
- Customizable layouts
- Customizable display
- Use touch sound
- Press and hold the result to copy to clipboard
- Vibrates when the widget is tapped
- Set the rounding of decimals
- To see the date of a past calculation, long click on the one you want
- To remove a past calculation from the list, swipe it right or left
----------------------------------------------------------------------------------------------------

**Comment by amorenew** [comment]
@rehammetwally well done, you did a great effort .
Do you will make the wireframes or just the system analysis ?

**Comment by rehammetwally** [comment]
wireframes also

**Comment by amorenew** [comment]
That's great

**Comment by rehammetwally** [comment]
Wireframes: 
https://ninjamock.com/s/5VDC1

**Comment by amorenew** [comment]
@rehammetwally 
as it's just 1 screen no need for prototype 
wireframe is more than enough
https://github.com/amorenew/awesome-calculator/issues/2

**Comment by amorenew** [comment]
Portrait wireframe
![clac_wireframe_portrait](https://user-images.githubusercontent.com/2842459/27100574-499558d0-5087-11e7-9ef4-3ff8fa771b9b.png)

Landscape wireframe

![clac_wireframe_landscape](https://user-images.githubusercontent.com/2842459/27100597-58ebaf3c-5087-11e7-9fb0-39d869736fc4.png)

**Comment by amorenew** [comment]
@AhmedAtia39 
I will make a video tomorrow about the progress .
then I will add all tasks bussiness, UI , Testing, Unit Testing, etc
Just wait tomorrow and after video you will get more information and tasks details.

**Comment by AhmedAtia39** [comment]
ok .. we will wait your video
بتاريخ ٢٠١٧/٠٦‏/١٣ ١٠:٠٧ م، كتب "Amr Abd El Wahab El Desouky" <
notifications@github.com>:

**Comment by amorenew** [comment]
@rehammetwally In history button what will be the scenario or how it could be displayed?

**Comment by AhmedAtia39** [comment]
see this

2017-06-14 9:34 GMT+02:00 Amr Abd El Wahab El Desouky <
notifications@github.com>:

**Comment by AhmedAtia39** [comment]
​

2017-06-14 23:35 GMT+02:00 Ahmed Atia <ahmedatia689@gmail.com>:
