### ISSUE TITLE
Business Logic - Math calculation helper

### ISSUE THREAD

**Issue by amorenew** [amorenew/awesome-calculator#10]
- [ ] Make a helper class for different math calculation the name could be like MathHelper
all method should be static so I just call like this MathHelper.square(number) which mean  x^2

- [ ] Add all the functions that on the wireframes like Addition, subtraction, multiplication, division, cos, tan, sin, etc
```
Task Rules:
1-Mention that you want the task.
2-Mention the estimated time to finish it.
```

**Comment by amorenew** [comment]
Could be helpful sample:
https://inducesmile.com/android/how-to-create-android-scientific-calculator-application/

**Comment by HassanHamdy** [comment]
i will take this task but please mention me all the functions should i implement to determine the estimated time to finish

**Comment by amorenew** [comment]
@rehammetwally  could you tell him required math functions so he can implement it in the helper class

**Comment by rehammetwally** [comment]
addition, subtraction, multiplication, division
,cubeRoot,squareRoot,pi,naturalLogarithm
,exponential , base2Logarithm,base10Logarithm
,sin , cos, tan
,inverseSin , inverseCos, inverseTan
clear,getHistory,modulus

**Comment by HassanHamdy** [comment]
@amorenew @rehammetwally  please check the uploaded class, i have added other operations than specified above.
please trace it again and if there is error send it to me.

**Comment by amorenew** [comment]
@HassanHamdy I will open a new Issue for review
