### ISSUE TITLE
Review Business Logic - Math calculation helper

### ISSUE THREAD

**Issue by amorenew** [amorenew/awesome-calculator#12]
- [ ] Review Naming Convention for Classes, Methods, Variables and etc
- [ ] Review Object Oriented Programming like Encapsulation
- [ ] Review Clean Code like comments

**Comment by amorenew** [comment]
@HassanHamdy 
Class Name: helperClass give it more descriptive name
Method Names: Addition and others make them verbs not nouns like add or plus and so on
Inverse_Sin avoid underscore "_" in method names
Base_2_Logarithm could be Log2
AnyBaseLogarithm could be LogN or just Log so you can apply overloading here
search for Method Overloading in Java
Add simple comments for the class and the methods 
just one line comment is Enough by Java document style 
/**
 *
 */
it will appear on the auto-complete popup information when someone uses your method

**Comment by HassanHamdy** [comment]
@amorenew 
ok and are you check result of each function again ??

**Comment by amorenew** [comment]
@HassanHamdy some of them are from Math class directly so no need to test it 
but maybe we will test more if we have a tester.
I only review the code not the functionality
Don't worry we will find a testers later

**Comment by HassanHamdy** [comment]
@amorenew check and i added power function
